"""add assistant knowledge files

Revision ID: 359039e39387
Revises: 5d2b8cebb390
Create Date: 2026-07-21 18:21:42.744416
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "359039e39387"
down_revision: str | None = "5d2b8cebb390"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assistant_files",
        sa.Column("assistant_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["assistant_id"],
            ["assistants.id"],
            name=op.f("fk_assistant_files_assistant_id_assistants"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_assistant_files_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assistant_files")),
        sa.UniqueConstraint(
            "assistant_id", "file_id", name=op.f("uq_assistant_files_assistant_id")
        ),
    )
    op.create_index(
        op.f("ix_assistant_files_assistant_id"), "assistant_files", ["assistant_id"], unique=False
    )
    op.create_index(
        op.f("ix_assistant_files_file_id"), "assistant_files", ["file_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_assistant_files_file_id"), table_name="assistant_files")
    op.drop_index(op.f("ix_assistant_files_assistant_id"), table_name="assistant_files")
    op.drop_table("assistant_files")
    # ### end Alembic commands ###
