"""add tool executions and message attachments

Revision ID: 5d2b8cebb390
Revises: a6acff34fab8
Create Date: 2026-07-21 17:00:21.132310
"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

revision: str = "5d2b8cebb390"
down_revision: str | None = "a6acff34fab8"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_attachments",
        sa.Column("message_id", sa.Uuid(), nullable=False),
        sa.Column("file_id", sa.Uuid(), nullable=False),
        sa.Column("attachment_type", sa.String(length=30), nullable=False),
        sa.Column("attachment_metadata", sa.JSON(), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["file_id"],
            ["files.id"],
            name=op.f("fk_message_attachments_file_id_files"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_message_attachments_message_id_messages"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_message_attachments")),
        sa.UniqueConstraint(
            "message_id", "file_id", name=op.f("uq_message_attachments_message_id")
        ),
    )
    op.create_index(
        op.f("ix_message_attachments_file_id"), "message_attachments", ["file_id"], unique=False
    )
    op.create_index(
        op.f("ix_message_attachments_message_id"),
        "message_attachments",
        ["message_id"],
        unique=False,
    )
    op.create_table(
        "tool_executions",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("tool_id", sa.Uuid(), nullable=False),
        sa.Column("message_id", sa.Uuid(), nullable=True),
        sa.Column("input_data", sa.JSON(), nullable=False),
        sa.Column("output_data", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["message_id"],
            ["messages.id"],
            name=op.f("fk_tool_executions_message_id_messages"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["tool_id"],
            ["tool_definitions.id"],
            name=op.f("fk_tool_executions_tool_id_tool_definitions"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_tool_executions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_tool_executions")),
    )
    op.create_index(
        op.f("ix_tool_executions_created_at"), "tool_executions", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_tool_executions_message_id"), "tool_executions", ["message_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_executions_tool_id"), "tool_executions", ["tool_id"], unique=False
    )
    op.create_index(
        op.f("ix_tool_executions_user_id"), "tool_executions", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_tool_executions_user_id"), table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_tool_id"), table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_message_id"), table_name="tool_executions")
    op.drop_index(op.f("ix_tool_executions_created_at"), table_name="tool_executions")
    op.drop_table("tool_executions")
    op.drop_index(op.f("ix_message_attachments_message_id"), table_name="message_attachments")
    op.drop_index(op.f("ix_message_attachments_file_id"), table_name="message_attachments")
    op.drop_table("message_attachments")
    # ### end Alembic commands ###
